language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - chmod +x mvnw

#before_install:
#  - chmod +x mvnw
 # - mysql -u root password admin
  #- mysql -u root -e "CREATE USER 'aran'@'localhost' IDENTIFIED BY 's3cr3t';"
  #- mysql -u root -e "GRANT ALL ON user.* TO 'aran'@'localhost';"
 # - mysql -e 'CREATE DATABASE IF NOT EXISTS users_db;'
  - mysql -u root --password="" < test/travis.sql

dist: trusty

script:
  - sudo ./mvnw clean install

#dist: precise
